export const GET_ALL= "GET_ALL";
export const FILTERED_BY_DIETS= "FILTERED_BY_DIETS";
export const FILTERED_BY_SOURCE= "FILTERED_BY_SOURCE";
export const ORDERED_BY_NAME= "ORDERED_BY_NAME";
export const ORDERED_BY_SCORE= "ORDERED_BY_SCORE";
export const CREATE_RECIPE= "CREATE_RECIPE";